# Prefix Key (Ctrl + A)
unbind C-b
set -g prefix C-a

# Base Index (Windows & Panes)
set -g base-index 1
set -g pane-base-index 1

# Enable Mouse Support
set -g mouse on

# Enable Vi Commands in Copy Mode
set-window-option -g mode-keys vi

# Increase Histroy Limit
set -g history-limit 100000

# Copy Text to System Clipboard
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# New Windows/Pane in $PWD
bind c new-window -c "#{pane_current_path}"

# Prevent Automatic Window Renaming
set-option -g allow-rename off

# Split Ppanes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Switch Panes using Alt-arrow without Prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
