# Prefix Key (Ctrl + A)
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Enable 256 Colors
set -g default-terminal "screen-256color"

# Reload .tmux.conf file
bind r source-file ~/.tmux.conf \; display "Configuration Reloaded!"

# Base Index (Windows & Panes)
set -g base-index 1
set -g pane-base-index 1

# Enable Mouse Support
set -g mouse on

# Enable Vi Commands in Copy Mode
set-window-option -g mode-keys vi

# Increase Histroy Limit
set -g history-limit 100000

# Copy Text to System Clipboard
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# New Windows/Pane in $PWD
bind c new-window -c "#{pane_current_path}"

# Prevent Automatic Window Renaming
set-option -g allow-rename off

# Split Ppanes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Switch Panes using Alt-arrow without Prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Status Bar Configuration
set -g status 'on'
set -g status-bg 'colour235'
set -g status-justify 'centre'
set -g status-left-length '100'
set -g status-right-length '100'
set -g message-style fg='colour222',bg='colour238'
set -g message-command-style fg='colour222',bg='colour238'
set -g pane-border-style fg='colour238'
set -g pane-active-border-style fg='colour154'
setw -g window-status-activity-style fg='colour154',bg='colour235',none
setw -g window-status-separator ''
setw -g window-status-style fg='colour121',bg='colour235',none
set -g status-left '#[fg=colour232,bg=colour154] #S #[fg=colour154,bg=colour238,nobold,nounderscore,noitalics]#[fg=colour222,bg=colour238] #W #[fg=colour238,bg=colour235,nobold,nounderscore,noitalics]#[fg=colour121,bg=colour235] #(whoami)  #[fg=colour235,bg=colour235,nobold,nounderscore,noitalics]'
set -g status-right '#[fg=colour235,bg=colour235,nobold,nounderscore,noitalics]#[fg=colour121,bg=colour235] %r  %a  %Y #[fg=colour238,bg=colour235,nobold,nounderscore,noitalics]#[fg=colour222,bg=colour238] #H #[fg=colour154,bg=colour238,nobold,nounderscore,noitalics]#[fg=colour232,bg=colour154] #(rainbarf --battery --remaining --no-rgb) '
setw -g window-status-format '#[fg=colour235,bg=colour235,nobold,nounderscore,noitalics]#[default] #I  #W #[fg=colour235,bg=colour235,nobold,nounderscore,noitalics]'
setw -g window-status-current-format '#[fg=colour235,bg=colour238,nobold,nounderscore,noitalics]#[fg=colour222,bg=colour238] #I  #W  #F #[fg=colour238,bg=colour235,nobold,nounderscore,noitalics]'
